owner: mchaNetwork
repo: status

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipPoweredByReadme: true

commitMessages:
  commitAuthorName: "mochaaP Bot"
  commitAuthorEmail: "git-bot@mochaa.ws"

sites:
  - name: Homepage
    url: https://mochaa.ws
    icon: https://avatars.githubusercontent.com/u/21154023
  - name: Insights
    url: https://insights.mcha.cloud
    icon: https://insights.mcha.cloud/static/dashboard/images/icon.00463752afd0.png
  - name: GitHub Mirror
    url: https://gh.chapro.xyz
    icon: https://favicons.githubusercontent.com/github.com
  - name: OpenWrt Mirror
    url: https://mirrors.chapro.xyz/openwrt/
    icon: https://favicons.githubusercontent.com/wiki.openwrt.org
  - name: Wikipedia Mirror
    url: https://wei-ji.eu.org/
  - name: Captive Portal
    url: https://captive.mcha.cloud/generate/android
    expectedStatusCodes:
      - 204

assignees:
  - mochaaP

status-website:
  cname: status.mcha.cloud
  themeUrl: https://assets.mcha.network/status/style.css
  logoUrl: https://assets.mcha.network/img/branding/network.png
  favicon: https://assets.mcha.network/img/branding/favicon.png
  name: mochaaNetwork
  introTitle: "mochaaNetwork System Status"
  introMessage: |
    Welcome to the status monitor for public-facing mochaaNetwork services.
    Here, you can check the current status of our services and get the latest
    updates on any incidents or maintenance work that may impact our users.
    Our goal is to keep you informed and minimize any disruptions to your
    experience while using our services.
    Feel free to bookmark this page or subscribe to our RSS feed. Thank you
    for your patience and understanding.
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://mcha.cloud/
  customBodyHtml: '<script async src="https://insights.mcha.cloud/script.js" data-account-id="0a56e2d5-8ea5-4e46-a7ec-1e96361b392d"></script>'

user-agent: mchaNtwk

i18n:
  footer: © mochaaNetwork

