owner: mchaNetwork
repo: status

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipPoweredByReadme: true

commitMessages:
  commitAuthorName: "mcha0[bot]"
  commitAuthorEmail: "git-bot@mochaa.ws"

sites:
  - name: homepage
    url: https://mochaa.ws
    icon: https://avatars.githubusercontent.com/u/21154023
  - name: insights
    url: https://insights.mcha.cloud/healthz
    icon: https://raw.githubusercontent.com/offen/offen/development/server/public/static/offen-icon-black.svg
  - name: searcha
    url: https://sear.mcha.cloud/healthz
    icon: https://raw.githubusercontent.com/searxng/searxng/master/searx/static/themes/simple/img/favicon.svg
  - name: wakapi
    url: https://waka.mcha.cloud/api/health
    icon: https://raw.githubusercontent.com/muety/wakapi/master/static/assets/images/apple-touch-icon.png
    __dangerous__body_down_if_text_missing: "app=1"
    __dangerous__body_degraded_if_text_missing: "db=1"
  - name: fluxfeed
    url: https://flux.mcha.cloud/healthcheck
    icon: https://raw.githubusercontent.com/miniflux/v2/main/internal/ui/static/bin/favicon-32.png
  - name: GitHub Mirror
    url: https://gh.chapro.xyz
    icon: https://raw.githubusercontent.com/mchaNetwork/github-proxy/trunk/src/favicon.svg
  - name: Wikipedia Mirror (Wikiless)
    url: https://wei-ji.eu.org/
    icon: https://raw.githubusercontent.com/Metastem/wikiless/main/static/wikiless-favicon.ico
  - name: Twitter Mirror (Nitter)
    url: https://tui-te.eu.org/Jack/status/20
    icon: https://raw.githubusercontent.com/zedeus/nitter/master/public/logo.png
  - name: Reddit Mirror (Redlib)
    url: https://hong-di.eu.org/
    icon: https://raw.githubusercontent.com/redlib-org/redlib/main/static/favicon.png
  - name: Yet Another LLM UI
    url: $YALLMUI_URL
    icon: https://github.com/mchaNetwork/status/assets/21154023/9304428c-412c-4acf-8b6c-1e370d602cef
    __dangerous__body_down_if_text_missing: '"success":true'

assignees:
  - mochaaP

status-website:
  cname: status.mcha.cloud
  themeUrl: https://status.mcha.cloud/style.css
  favicon: https://status.mcha.cloud/favicon.png
  logoUrl: https://avatars.githubusercontent.com/u/61316859
  name: monitar - mchantwk status
  navbar:
    - title: Home
      href: https://mcha.cloud/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/mchaNetwork
  customHeadHtml: '<script async src="https://insights.mcha.cloud/script.js" data-account-id="0a56e2d5-8ea5-4e46-a7ec-1e96361b392d"></script>'

user-agent: Mozilla/5.0 (compatible; monitar/1.0; +https://status.mcha.cloud)

i18n:
  footer: © mochaaNetwork
